### ISSUE TITLE
NOOB AGAIN

### ISSUE THREAD

**Issue by sahilm10** [cnlohr/esp8266_dmx_explorer#2]
flashed it to nodemcu with esp82xx toolchain. flashed fine but it does create any new AP to connect too, it just blinks fast. I don't know what I am doing wrong here. Tired to serial monitor it, it shows this msg

>> 0x3fc,0x3fc000rf_cal[0] !=0x05,is 0x00

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x40100000, len 26256, room 16 
tail 0
chksum 0x98
load 0x3ffe8000, len 1304, room 8 
tail 0
chksum 0x8b
load 0x3ffe8520, len 2720, room 8 
tail 8
chksum 0x11
csum 0x11
mismatch map 2,spi_size_map 4
boot not set
ota1 not set
ota2 not set
system_partition_table_regist 4 success!!

**Comment by cnlohr** [comment]
This one's relatively easy!

From a terminal:
```
make burnitall
```

Your ESP has old init rom data.

**Comment by sahilm10** [comment]
okay, it works now, thank you. But now how do I send UDP packets to esp8266,
I compiled colorchord2 with tcc and it works fine and then I edited "netlight-dmx.conf" to esp8266's ip
what do I need to do next?  need help!!

and plus I'm testing it on ws2812B so I hooked up the tx pin to data pin of ws2812B
I'm pretty sure I'm not supposed to do that but idk just shooting arrows in the dark.

**Comment by sahilm10** [comment]
how do I send UDP packets to esp8266
